INSERT INTO ACADEMIC_CALENDAR VALUES (CALENDAR_ID_SEQ.NEXTVAL, 2017, SYSDATE,SYSDATE+1,'1학기 수강신청');
INSERT INTO ACADEMIC_CALENDAR VALUES (CALENDAR_ID_SEQ.NEXTVAL, 2017, SYSDATE,SYSDATE+1,'1학기 휴복학신청');
INSERT INTO ACADEMIC_CALENDAR VALUES (CALENDAR_ID_SEQ.NEXTVAL, 2017, SYSDATE,SYSDATE+1,'1학기 학점포기신청');

select CALENDAR_ID_SEQ.NEXTVAL from dual;